# Generated by Django 4.1.4 on 2022-12-22 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GymMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership', models.CharField(blank=True, max_length=15, null=True)),
                ('instructor', models.CharField(blank=True, max_length=50, null=True)),
                ('time', models.CharField(blank=True, max_length=10, null=True)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GymMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=40, null=True)),
                ('phone', models.IntegerField()),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymManager.gymmembership')),
            ],
        ),
    ]
